[package]
name = "kafka_client"
version = "0.1.0"
edition = "2021"

[dependencies]
kafkang = "0.2.1"
tokio = {version = "1.49.0", features = ["full"]}
structopt = "0.3.26"
log = "0.4.29"
env_logger = "0.11.9"
anyhow = "1.0.101"
